# numpy tutorial 

## broadcasting

In [1]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])

In [10]:
arr1 + arr2

array([4, 6, 8])

In [11]:
arr1 + 4

array([5, 6, 7])

In [14]:
arr3 = np.array([1,2,3])
arr3

array([1, 2, 3])

In [15]:
arr4 = np.array([[2],[4],[6]])
arr4

array([[2],
       [4],
       [6]])

In [16]:
arr3 + arr4

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

## broadcasting rules

In [17]:
arr5 = np.array([1,2,3])
arr6 = np.array([4,5,6,7])
arr5 + arr6

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
### both should be same shape
### if not same shape - at least one of them dimension should be  1

In [19]:
arr7 = np.array([[1,2,3],[4,5,6]])
arr1.ndim


1

In [20]:
arr8 = np.array([2,2,2])
arr8.ndim

1

In [23]:
arr7 + arr8 

array([[3, 4, 5],
       [6, 7, 8]])

In [24]:
arr9 = np.array([[1,2],[3,4],[5,6]])
arr10 =np.array([2,2,2])
arr9 + arr10

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# generating random numbers

In [26]:
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg

In [28]:
arr_rg = gen(pcg(seed=99))
arr_rg.normal(size=(5,5))

array([[ 0.0824943 , -0.46441841,  0.05051506,  0.68623082, -1.75679051],
       [ 1.6844316 , -0.45784284, -0.59642009, -1.04696756,  0.93179202],
       [ 0.67498048,  1.2444412 ,  0.89308742,  0.26300494,  0.32851785],
       [ 0.93524369, -0.87761299, -0.04589609,  0.38187174, -0.45253897],
       [ 0.72166488, -0.35216341,  0.67279702,  0.14062329,  0.46256068]])

In [30]:
arr_rg = gen(pcg(seed=200))
arr_rg.integers(low=10, high=100, size=(5,5))

array([[13, 68, 31, 69, 40],
       [12, 58, 26, 90, 61],
       [49, 59, 52, 57, 52],
       [43, 73, 15, 70, 43],
       [50, 42, 72, 31, 66]])

In [31]:
arr_rg = gen(pcg(seed=200))
arr_rg.random(size=(5,5))

array([[0.64683414, 0.66391997, 0.02990165, 0.17783134, 0.57349665],
       [0.55116402, 0.52692044, 0.37424281, 0.0607941 , 0.36999257],
       [0.35751452, 0.24155704, 0.04417303, 0.90875759, 0.5267329 ],
       [0.11358564, 0.14124115, 0.44684772, 0.50149127, 0.78536388],
       [0.04118076, 0.27194012, 0.84968852, 0.91967885, 0.56165551]])

# indexing and slicing 

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
arr 


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0]

array([1, 2, 3])

In [34]:
arr[1]

array([4, 5, 6])

In [40]:
arr[1][2]
### x[row,column]

np.int64(6)

In [41]:
arr11 = np.array([1,2,3])
arr11[-1]

np.int64(3)

In [43]:
arr[1,2] = 9
arr

array([[1, 2, 3],
       [4, 5, 9]])

In [44]:
arr[1] = 7 
arr

array([[1, 2, 3],
       [7, 7, 7]])

In [45]:
arr[0] + 2 

array([3, 4, 5])

In [46]:
arr 

array([[1, 2, 3],
       [7, 7, 7]])